### ISSUE TITLE
Can't clone the repository

### ISSUE THREAD

**Issue by vieira-temes** [tgoetten/mailarchiva-dockerized#1]
I'm trying to clone the repository on Ubuntu 20.04. I don't remember having to provide a user/password to clone a git repository in the past, but I'm a github newbie. This is the terminal output:

```
$ git clone https://github.com/tgoetten/mailarchiva-docker.git
Cloning into 'mailarchiva-docker'...
Username for 'https://github.com': PabloGrok
Password for 'https://PabloGrok@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/tgoetten/mailarchiva-docker.git/'
```

I'm using a Personal Token as password.

Can you please help?

**Comment by tgoetten** [comment]
Hey @PabloGrok,
thanks for the feedback. I checked again the access settings for this repository and they seem to be correct.

﻿The only explanation I can think of would be that you have a credential helper installed that tries to fill in your credentials for all connections to Github. 

Does `ssh -T git@github.com` work for you?

**Comment by vieira-temes** [comment]
> ﻿The only explanation I can think of would be that you have a credential helper installed that tries to fill in your credentials for all connections to Github.

I don't have that. I don't even know what that is.


> Does `ssh -T git@github.com` work for you?

Nope.

```
$ ssh -T git@github.com
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
```
I must insist this is the first time a `git clone` command asks me for a user/pass. Is this intentional on your side?

**Comment by tgoetten** [comment]
Because you receive an error running `ssh -T git@github.com` it's not an issue with this repository but rather with your Github / SSH config.

I recommend to follow the steps mentioned here https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey . They are meant to solve issues related to your error message
`Permission denied (publickey).`

**Comment by vieira-temes** [comment]
Nevermind. It's working normally now. It seems I was using git as root and all my problems stem from that.

**Comment by tgoetten** [comment]
> Nevermind. It's working normally now. It seems I was using git as root and all my problems stem from that.

Great to hear that you managed to solve it. May I close this issue as solved?
